{"uuid": "557990ec-afed-42dc-ade5-c26844558e61", "children": ["55e48a00-1a7a-45bb-aa95-dbf74755b84d"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "TypeError: enable_wlan() got an unexpected keyword argument 'key'\n", "trace": "  File \"/home/nikita/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/nikita/candela_projects/6052_branch_check/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, run_lf, instantiate_profile, get_configuration, get_markers, lf_tools)\n  File \"/home/nikita/candela_projects/6052_branch_check/wlan-testing/tests/fixtures_3x.py\", line 149, in setup_profiles\n    instantiate_profile_obj.enable_wlan(id=\"1\", wlan=lf_dut_data[0]['ssid_name'],\n"}, "start": 1645092946780, "stop": 1645093019255}], "start": 1645092946780, "stop": 1645093019396}