{"uuid": "c2f50de5-f8a7-41d9-b9f4-a5b5c2795e00", "children": ["490a960d-fb1e-4c01-9101-5bd41d957ae3"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "TypeError: enable_wlan() got an unexpected keyword argument 'key'\n", "trace": "  File \"/home/nikita/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/nikita/candela_projects/6052_branch_check/wlan-testing/tests/e2e/basic/conftest.py\", line 77, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, run_lf, instantiate_profile, get_configuration, get_markers, lf_tools)\n  File \"/home/nikita/candela_projects/6052_branch_check/wlan-testing/tests/fixtures_3x.py\", line 185, in setup_profiles\n    instantiate_profile_obj.enable_wlan(id=\"2\", wlan=lf_dut_data[1]['ssid_name'], wlanssid=lf_dut_data[1]['ssid_name'], key=lf_dut_data[1]['security_key'])\n"}, "start": 1645093305683, "stop": 1645093495509}], "start": 1645093305682, "stop": 1645093495657}